# Generated by Django 2.2 on 2020-02-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_refund'),
        ('core', '0005_auto_20200212_2319'),
    ]

    operations = [
    ]
