# Generated by Django 2.2.10 on 2020-02-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200222_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
    ]
