# Generated by Django 2.2.10 on 2020-02-21 19:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_billingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='India', max_length=2),
        ),
    ]
